version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Running pre-build actions...
  build:
    commands:
      - echo Building the project...
  post_build:
    commands:
      - echo Post-build actions...
      - echo Build completed on `date`
